# Generated by Django 5.0.7 on 2024-07-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_price_product_prics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prics',
            new_name='prices',
        ),
    ]
